#!/bin/sh

if `echo "$(uncrustify --version)" | grep -w -i "uncrustify 0.59" 1>/dev/null 2>&1`; then
	version=$(echo "$(uncrustify --version)")
	echo
	echo "$version"
	echo
else
	version=$(echo "$(uncrustify --version)")
	echo 
	echo
	echo "Error: Incorrect version of uncrustify - $version"
	echo
	exit -1
fi
